baseURL = "https://keda.sh"
languageCode = "en-us"
title = "KEDA"
enableGitInfo = true
disableKinds = ["taxonomy", "taxonomyTerm"]

# See other available styles here: https://xyproto.github.io/splash/docs/
[markup.highlight]
style = "dracula"

[params]
# Main page hero
tagline = "Kubernetes Event-driven Autoscaling"
description = "Application autoscaling made simple"

# "What is KEDA?" section on main page
what_is = """
**KEDA** is a [Kubernetes](https://kubernetes.io)-based Event Driven Autoscaler. With KEDA, you can drive the scaling of any container in Kubernetes based on the number of events needing to be processed.

**KEDA** is a single-purpose and lightweight component that can be added into any Kubernetes cluster. KEDA works alongside standard Kubernetes components like the [Horizontal Pod Autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) and can extend functionality without overwriting or duplication. With KEDA you can explicitly map the apps you want to use event-driven scale, with other apps continuing to function.  This makes KEDA a flexible and safe option to run alongside any number of any other Kubernetes applications or frameworks.
"""

locale = "en_US"
twitter_handle = "kedaorg"
font_awesome_version = "5.12.1"
alpine_js_version = "2.2.1"
favicon = "favicon.png"

[params.versions]
docs = ["2.4", "2.3", "2.2", "2.1", "2.0", "1.5", "1.4"]

# Site fonts. For more options see https://fonts.google.com.
[[params.fonts]]
name = "Inria Sans"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[params.fonts]]
name = "Roboto Mono"
sizes = [300, 400, 600, 700]
type = "monospace"

# All logos are in static/img/logos
[params.logos]
navbar = "keda-horizontal-color.png"
hero = "keda-icon-color.png"
footer = "keda-icon-white.png"

[mediaTypes."text/netlify"]
delimiter = ""

[outputFormats.REDIRECTS]
mediaType = "text/netlify"
baseName = "_redirects"

[outputs]
home = [ "HTML", "REDIRECTS" ]

# "Highlighted Samples" section on the main page
[[params.samples]]
title = "RabbitMQ and Go"
content = "RabbitMQ Consumer written in Go that is scaled with KEDA."
url = "https://github.com/kedacore/sample-go-rabbitmq"
icon = "fas fa-envelope"

[[params.samples]]
title = "Azure Functions and Queue"
content = "Azure Function that triggers on Azure Storage Queues."
url = "https://github.com/kedacore/sample-hello-world-azure-functions"
icon = "fas fa-bolt"

[[params.samples]]
title = ".NET Core worker and Azure Service Bus"
content = "Scale a .NET Core worker based on an Azure Service Bus queue."
url = "https://github.com/kedacore/sample-dotnet-worker-servicebus-queue"
icon = "fas fa-cloud"

# Social media buttons
[[params.social]]
name = "Twitter"
icon = "fab fa-twitter"
bg_color = "twitter-blue"
icon_color = "white"
text_color = "white"
url = "https://twitter.com/kedaorg"

[[params.social]]
name = "GitHub"
icon = "fab fa-github"
bg_color = "white"
icon_color = "black"
text_color = "black"
url = "https://github.com/kedacore/keda"

[[params.social]]
name = "Slack"
icon = "fab fa-slack"
bg_color = "slack-green"
icon_color = "white"
text_color = "white"
url = "https://kubernetes.slack.com/messages/CKZJ36A5D"

# Main page hero buttons
[[menu.buttons]]
url = "/docs/concepts"
name = "Concepts"
pre = "fas fa-stream"
weight = 1

[[menu.buttons]]
url = "/docs/deploy"
name = "Deploying KEDA"
pre = "fas fa-play-circle"
weight = 2

[[menu.buttons]]
url = "/docs/concepts/#architecture"
name = "Architecture"
pre = "fas fa-project-diagram"
weight = 3

[[menu.buttons]]
url = "/docs/scalers"
name = "Scalers"
pre = "fas fa-ruler-vertical"
weight = 4

[[menu.buttons]]
url = "/blog"
name = "Blog"
pre = "fa fa-rss"
weight = 5

# Navbar and footer menu
[[menu.docs]]
url = "/docs/"
name = "Docs"
identifier = "docs"
weight = 1

[[menu.docs]]
url = "/docs/deploy"
name = "Deploying KEDA"
parent = "docs"
weight = 1

[[menu.docs]]
url = "/docs/concepts/"
name = "Concepts"
parent = "docs"
weight = 2

[[menu.docs]]
url = "/docs/concepts/#architecture"
name = "Architecture"
parent = "docs"
weight = 3

[[menu.docs]]
url = "/docs/operate/"
name = "Operate"
parent = "docs"
weight = 4

[[menu.docs]]
url = "/docs/migration/"
name = "Migration Guide"
parent = "docs"
weight = 5

[[menu.docs]]
url = "/docs/faq/"
name = "FAQ"
parent = "docs"
weight = 6

[[menu.docs]]
url = "/docs/troubleshooting/"
name = "Troubleshooting"
parent = "docs"
weight = 7

[[menu.main]]
url = "/blog"
name = "Blog"
weight = 2

[[menu.main]]
url = "/community/"
name = "Community"
weight = 3

[[menu.main]]
name = "Project"
identifier = "project"
weight = 4

[[menu.main]]
url = "/resources/"
name = "Learning Resources"
parent = "project"
weight = 1

[[menu.main]]
url = "https://github.com/cncf/foundation/blob/master/code-of-conduct.md"
name = "Code of Conduct"
parent = "project"
weight = 2

[[menu.main]]
url = "https://github.com/kedacore/governance/blob/main/GOVERNANCE.md"
name = "Governance"
parent = "project"
weight = 3

[[menu.main]]
url = "https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md"
name = "Contributing"
parent = "project"
weight = 4

[[menu.main]]
url = "https://github.com/kedacore/keda/blob/main/CHANGELOG.md"
name = "Changelog"
parent = "project"
weight = 5

[[menu.main]]
url = "https://github.com/kedacore/governance/blob/main/MAINTAINERS.md"
name = "Maintainers"
parent = "project"
weight = 6

[[menu.main]]
url = "https://github.com/kedacore/governance/blob/main/BRANDING.md"
name = "Colors and Logos"
parent = "project"
weight = 7

[[menu.main]]
url = "https://github.com/kedacore/keda/blob/main/LICENSE"
name = "License"
parent = "project"
weight = 7

[[menu.main]]
url = "https://github.com/kedacore/samples"
name = "Samples"
weight = 5

[[menu.main]]
url = "https://merch.keda.sh/"
name = "Merch"
weight = 6

# "Features" section on the main page
[[params.features]]
title = "Event-driven"
content = "Intelligently scale your event-driven application"
icon = "fas fa-bolt"

[[params.features]]
title = "Autoscaling Made Simple"
content = "Bring rich scaling to every workload in your [Kubernetes](https://kubernetes.io) cluster"
icon = "fas fa-rocket"

[[params.features]]
title = "Built-in Scalers"
content = "Out-of-the-box scalers for various vendors, databases, messaging systems, telemetry systems, CI/CD, and more"
icon = "fas fa-cubes"

[[params.features]]
title = "Multiple Workload Types"
content = "Support for variety of workload types such as deployments, jobs & custom resources with `/scale` sub-resource"
icon = "fas fa-shapes"

[[params.features]]
title = "Vendor-Agnostic"
content = "Support for triggers across variety of cloud providers & products"
icon = "fas fa-cloud"

[[params.features]]
title = "Azure Functions Support"
content = "Run and scale your Azure Functions on Kubernetes in production workloads"
icon = "fab fa-microsoft"

# "Users" section on the Community page
[[params.users]]
url = "https://alibabacloud.com/"
logo = "alibaba-cloud.png"

[[params.users]]
url = "https://ampify.io/"
logo = "ampify-io.png"

[[params.users]]
url = "https://airflow.apache.org/"
logo = "apache-airflow.png"

[[params.users]]
url = "https://www.astronomer.io"
logo = "astronomer.svg"

[[params.users]]
url = "https://chattermill.com"
logo = "chattermill.png"

[[params.users]]
url = "https://www.cloud-trade.com"
logo = "cloud-trade.png"

[[params.users]]
url = "https://coralogix.com/"
logo = "coralogix.gif"

[[params.users]]
url = "https://fission.io/"
logo = "fission.png"
[[params.users]]
url = "https://github.com/hmcts/"
logo = "hmcts.png"

[[params.users]]
url = "https://www.intercept.cloud"
logo = "intercept.png"

[[params.users]]
url = "https://kendaxa.com"
logo = "kendaxa.png"

[[params.users]]
url = "https://home.kpmg/uk/en/home.html"
logo = "KPMG.jpeg"

[[params.users]]
url = "https://underthehood.meltwater.com/"
logo = "meltwater.png"

[[params.users]]
url = "https://metamaze.eu/"
logo = "metamaze.png"

[[params.users]]
url = "https://microsoft.com"
logo = "microsoft.png"

[[params.users]]
url = "https://www.mivation.com"
logo = "mivation-inc.png"

[[params.users]]
url = "https://www.theproindia.com"
logo = "pro-logo.svg"

[[params.users]]
url = "https://www.purefacts.com"
logo = "purefacts.png"

[[params.users]]
url = "https://roadwork.io"
logo = "roadwork.png"

[[params.users]]
url = "https://www.schrederhyperion.com"
logo = "schreder-hyperion.png"

[[params.users]]
url = "https://seldon.io/"
logo = "seldon.png"

[[params.users]]
url = "https://www.teamleader.eu"
logo = "teamleader.png"

[[params.users]]
url = "https://zapier.com"
logo = "zapier.png"

# "Partners" section on the Community page
[[params.partners]]
url = "https://microsoft.com"
logo = "microsoft.png"

[[params.partners]]
url = "https://redhat.com"
logo = "red-hat.png"

# "Supported by" section on the Community page
[[params.supportedby]]
url = "https://azure.microsoft.com/en-us/services/devops/"
logo = "azure-devops.png"

[[params.supportedby]]
url = "https://snyk.io"
logo = "snyk.png"

[[params.supportedby]]
url = "https://vexxhost.com"
logo = "vexxhost.png"
